<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ProductRealSeeder extends Seeder
{
    public function run(): void
    {
        $cats = Category::pluck('id', 'slug');

        $products = [
            // ========== Cerámicos ==========
            ['nombre' => 'Cerámico Nacional Serie Zen', 'descripcion' => 'Cerámico nacional para revestimiento de pared con diseño de círculos concéntricos en relieve.', 'codigo' => 'LLG 36090 B', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Cerámicos'], 'cantidad' => 50, 'precio' => 32.50, 'disponible' => true],
            ['nombre' => 'Cerámico Amaderado Paquetón Premium Honey', 'descripcion' => 'Cerámico con textura de madera natural para su colocación en paredes laterales.', 'codigo' => null, 'medidas' => '20x61 cm', 'marca' => 'San Lorenzo', 'category_id' => $cats['Cerámicos'], 'cantidad' => 40, 'precio' => 38.00, 'disponible' => true],
            ['nombre' => 'Cerámico Nacional Serie Onda Gris', 'descripcion' => 'Cerámico nacional de pared con diseño de patrón geométrico 3D (onda gris) con relieves dorados.', 'codigo' => 'LLG Onda Gris', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Cerámicos'], 'cantidad' => 45, 'precio' => 35.00, 'disponible' => true],
            ['nombre' => 'Cerámico Importado Serie Círculos Navidad Fusión', 'descripcion' => 'Cerámico importado para pared principal con diseño de círculos concéntricos con relieve y detalles dorados (patrón "bola Navidad").', 'codigo' => null, 'medidas' => '60x60 cm', 'marca' => null, 'category_id' => $cats['Cerámicos'], 'cantidad' => 30, 'precio' => 55.00, 'disponible' => true],
            ['nombre' => 'Cerámico Nacional Serie Ladrillo Café (Pared Superior)', 'descripcion' => 'Cerámico nacional para pared superior con diseño texturizado de ladrillo beige.', 'codigo' => 'LG 36071 A', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Cerámicos'], 'cantidad' => 50, 'precio' => 30.00, 'disponible' => true],
            ['nombre' => 'Cerámico Nacional Serie Ladrillo Café (Pared Inferior)', 'descripcion' => 'Cerámico nacional con diseño texturizado de ladrillo marrón/café para paredes principales o inferiores.', 'codigo' => 'LG 36071 B', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Cerámicos'], 'cantidad' => 50, 'precio' => 30.00, 'disponible' => true],
            ['nombre' => 'Cerámico Nacional Pasión White', 'descripcion' => 'Cerámico nacional para pared izquierda con textura con relieve tipo diamante.', 'codigo' => null, 'medidas' => '27x45 cm', 'marca' => 'San Lorenzo', 'category_id' => $cats['Cerámicos'], 'cantidad' => 35, 'precio' => 28.50, 'disponible' => true],
            ['nombre' => 'Cerámico Nacional Pasión Red', 'descripcion' => 'Cerámico nacional para pared derecha con acabado rojo brillante y relieve tipo diamante.', 'codigo' => null, 'medidas' => '27x45 cm', 'marca' => 'San Lorenzo', 'category_id' => $cats['Cerámicos'], 'cantidad' => 35, 'precio' => 28.50, 'disponible' => true],
            ['nombre' => 'Cerámico Nacional Hexágono Dorado', 'descripcion' => 'Cerámico o porcelanato nacional para pared principal con relieve geométrico hexagonal en color blanco.', 'codigo' => 'LG 36099', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Cerámicos'], 'cantidad' => 40, 'precio' => 34.00, 'disponible' => true],
            ['nombre' => 'Cerámico Nacional Patrón Geométrico Amaderado', 'descripcion' => 'Cerámico de pared derecha con diseño de patrón geométrico amaderado en tonos café.', 'codigo' => null, 'medidas' => null, 'marca' => 'San Lorenzo', 'category_id' => $cats['Cerámicos'], 'cantidad' => 35, 'precio' => 32.00, 'disponible' => true],
            ['nombre' => 'Cerámico Nacional Serie Flores Azul', 'descripcion' => 'Cerámico o porcelanato nacional para panel de fondo con diseño de flores azul.', 'codigo' => 'LPIE 66985', 'medidas' => '60x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Cerámicos'], 'cantidad' => 25, 'precio' => 48.00, 'disponible' => true],
            ['nombre' => 'Cerámico Nacional Estocolmo Gris', 'descripcion' => 'Cerámico nacional de pared base con textura pétrea en matices grises.', 'codigo' => 'LG 36043', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Cerámicos'], 'cantidad' => 50, 'precio' => 29.00, 'disponible' => true],
            ['nombre' => 'Cerámico Nacional Canvas Azul', 'descripcion' => 'Cerámico nacional para pared inferior izquierda con diseño Canvas Azul.', 'codigo' => null, 'medidas' => '27x45 cm', 'marca' => 'San Lorenzo', 'category_id' => $cats['Cerámicos'], 'cantidad' => 35, 'precio' => 27.00, 'disponible' => true],
            ['nombre' => 'Cerámico Nacional Larizza Blanco', 'descripcion' => 'Cerámico nacional para pared superior izquierda con diseño de patrón de pequeños cuadros/mosaico.', 'codigo' => null, 'medidas' => '27x45 cm', 'marca' => 'San Lorenzo', 'category_id' => $cats['Cerámicos'], 'cantidad' => 35, 'precio' => 27.00, 'disponible' => true],

            // ========== Porcelanatos ==========
            ['nombre' => 'Porcelanato Nacional LFG 66018', 'descripcion' => 'Porcelanato nacional con diseño de mármol gris veteado o gris claro. Utilizado transversalmente en el piso y paredes laterales de múltiples ambientes de la exhibición.', 'codigo' => 'LFG 66018', 'medidas' => '60x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Porcelanatos'], 'cantidad' => 80, 'precio' => 45.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Importado Fusión Gold', 'descripcion' => 'Porcelanato importado para pared principal con diseño tipo mármol Calacatta con vetas dramáticas en gris y dorado.', 'codigo' => null, 'medidas' => '60x60 cm', 'marca' => null, 'category_id' => $cats['Porcelanatos'], 'cantidad' => 40, 'precio' => 72.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Vitrificado Tallado Chispeado Blanco Beach', 'descripcion' => 'Porcelanato vitrificado tallado con efecto escarchado para revestimiento de pared blanca.', 'codigo' => 'AG 6001', 'medidas' => '60x60 cm', 'marca' => null, 'category_id' => $cats['Porcelanatos'], 'cantidad' => 35, 'precio' => 58.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Vitrificado Tallado Chispeado Negro', 'descripcion' => 'Porcelanato vitrificado tallado con efecto escarchado para pared negra, pared lateral o piso coordinado.', 'codigo' => 'AG 6002', 'medidas' => '60x60 cm', 'marca' => null, 'category_id' => $cats['Porcelanatos'], 'cantidad' => 35, 'precio' => 58.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Nacional Carrara Blanco', 'descripcion' => 'Porcelanato nacional para paredes y fondos con diseño Carrara Blanco de vetas grises suaves.', 'codigo' => 'WP 66061', 'medidas' => '60x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Porcelanatos'], 'cantidad' => 60, 'precio' => 42.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Vitrificado Importado Negro Absoluto', 'descripcion' => 'Porcelanato vitrificado importado para piso con diseño negro absoluto y efecto espejo.', 'codigo' => 'MBXD 600', 'medidas' => '60x60 cm', 'marca' => null, 'category_id' => $cats['Porcelanatos'], 'cantidad' => 30, 'precio' => 75.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Nacional Negro Mate', 'descripcion' => 'Porcelanato nacional para piso con acabado negro mate.', 'codigo' => 'LFG 66098', 'medidas' => '60x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Porcelanatos'], 'cantidad' => 45, 'precio' => 40.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Nacional Texturado Negro', 'descripcion' => 'Porcelanato nacional para piso con diseño texturado negro.', 'codigo' => 'LFG 66099', 'medidas' => '60x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Porcelanatos'], 'cantidad' => 45, 'precio' => 42.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Nacional Gris Mate', 'descripcion' => 'Porcelanato nacional para piso con diseño gris mate.', 'codigo' => 'WFG 66002', 'medidas' => '60x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Porcelanatos'], 'cantidad' => 50, 'precio' => 38.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Coordinado Blanco con Vetas', 'descripcion' => 'Porcelanato coordinado para piso con acabado blanco con vetas grises.', 'codigo' => null, 'medidas' => null, 'marca' => null, 'category_id' => $cats['Porcelanatos'], 'cantidad' => 40, 'precio' => 44.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Nacional LFG 66001', 'descripcion' => 'Porcelanato nacional para piso con diseño de mármol gris claro con veta suave y acabado mate/satinado.', 'codigo' => 'LFG 66001', 'medidas' => '60x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Porcelanatos'], 'cantidad' => 80, 'precio' => 45.00, 'disponible' => true],

            // ========== Tablones ==========
            ['nombre' => 'Porcelanato Importado Madera Nevado', 'descripcion' => 'Porcelanato amaderado importado de pasta blanca de alta resistencia para revestimiento de paredes laterales o pisos coordinados.', 'codigo' => null, 'medidas' => '60x60 cm', 'marca' => 'Taylor', 'category_id' => $cats['Tablones'], 'cantidad' => 30, 'precio' => 65.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Coordinado Piedra Caliza', 'descripcion' => 'Tipo cerámico o porcelanato coordinado con fachaleta, con diseño de piedra caliza multicolor (gris/marrón).', 'codigo' => null, 'medidas' => null, 'marca' => null, 'category_id' => $cats['Tablones'], 'cantidad' => 25, 'precio' => 52.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Nacional Paquetón Golden', 'descripcion' => 'Porcelanato o cerámico amaderado nacional para pared lateral.', 'codigo' => null, 'medidas' => '20x61 cm', 'marca' => 'San Lorenzo', 'category_id' => $cats['Tablones'], 'cantidad' => 35, 'precio' => 42.00, 'disponible' => true],

            // ========== Revestimientos para pared ==========
            ['nombre' => 'Cerámico Nacional Blanco Brillante', 'descripcion' => 'Cerámico nacional para pared base con acabado blanco brillante.', 'codigo' => 'LG 36001', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Revestimientos para pared'], 'cantidad' => 60, 'precio' => 25.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Importado Calafate Grey', 'descripcion' => 'Porcelanato importado para pared principal o base con diseño de mármol blanco con vetas grises suaves.', 'codigo' => '311007995', 'medidas' => '30x60 cm', 'marca' => 'Taylor', 'category_id' => $cats['Revestimientos para pared'], 'cantidad' => 30, 'precio' => 48.00, 'disponible' => true],
            ['nombre' => 'Fachaleta para Pared Piedra Caliza', 'descripcion' => 'Fachaleta decorativa para pared lateral con diseño que emula piedra caliza.', 'codigo' => null, 'medidas' => '30x60 cm', 'marca' => null, 'category_id' => $cats['Revestimientos para pared'], 'cantidad' => 25, 'precio' => 42.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Importado Almudena Claro', 'descripcion' => 'Porcelanato importado para pared con acabado marmoleado y vetas en tonos crema, ocre y marrón.', 'codigo' => '311012262', 'medidas' => '30x60 cm', 'marca' => 'Taylor', 'category_id' => $cats['Revestimientos para pared'], 'cantidad' => 30, 'precio' => 50.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Nacional Onda Negro', 'descripcion' => 'Porcelanato nacional para pared lateral izquierda con relieve de ondas y vetas blancas tipo mármol sobre fondo negro.', 'codigo' => 'LG 36072 D', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Revestimientos para pared'], 'cantidad' => 40, 'precio' => 36.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Nacional Onda Gris', 'descripcion' => 'Porcelanato nacional para pared derecha de fondo con relieve de ondas con texturas internas.', 'codigo' => 'LG 36072 C', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Revestimientos para pared'], 'cantidad' => 40, 'precio' => 36.00, 'disponible' => true],

            // ========== Porcelanatos grandes ==========
            ['nombre' => 'Porcelanato Importado Esmeralda Dorado', 'descripcion' => 'Porcelanato importado para paredes con diseño de mármol blanco con vetas de gran formato en tonos dorado, ocre y azul profundo.', 'codigo' => 'JS 66J63', 'medidas' => '60x60 cm', 'marca' => null, 'category_id' => $cats['Porcelanatos grandes'], 'cantidad' => 20, 'precio' => 95.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Importado Trama Galaxia Negro', 'descripcion' => 'Porcelanato importado para pared de fondo derecho con diseño de relieve ondulado.', 'codigo' => null, 'medidas' => '60x60 cm', 'marca' => 'Typhoon', 'category_id' => $cats['Porcelanatos grandes'], 'cantidad' => 15, 'precio' => 88.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Importado Murete Aston', 'descripcion' => 'Porcelanato importado para pared con diseño texturizado de piedra apilada.', 'codigo' => null, 'medidas' => '60x60 cm', 'marca' => 'Typhoon', 'category_id' => $cats['Porcelanatos grandes'], 'cantidad' => 20, 'precio' => 85.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Importado Patrón Floral Negro', 'descripcion' => 'Porcelanato importado para panel central decorativo con patrón floral negro y detalles en oro (Floralia).', 'codigo' => null, 'medidas' => '60x120 cm', 'marca' => null, 'category_id' => $cats['Porcelanatos grandes'], 'cantidad' => 12, 'precio' => 120.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Importado Escarchado Gris', 'descripcion' => 'Porcelanato importado para pared principal con diseño de mármol blanco con vetas grises y chispas/escarchado dorado.', 'codigo' => 'JS 66 J 61', 'medidas' => '60x60 cm', 'marca' => null, 'category_id' => $cats['Porcelanatos grandes'], 'cantidad' => 18, 'precio' => 92.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Vitrificado Tallado Vincenzo', 'descripcion' => 'Porcelanato vitrificado tallado para pared lateral derecha con diseño Vincenzo.', 'codigo' => 'HG 60200006 PE', 'medidas' => '60x60 cm', 'marca' => null, 'category_id' => $cats['Porcelanatos grandes'], 'cantidad' => 15, 'precio' => 78.00, 'disponible' => true],
            ['nombre' => 'Porcelánica Importada Estudio Grafito', 'descripcion' => 'Revestimiento porcelánico importado para piso con diseño Estudio Grafito.', 'codigo' => null, 'medidas' => '60x60 cm', 'marca' => 'San Lorenzo', 'category_id' => $cats['Porcelanatos grandes'], 'cantidad' => 25, 'precio' => 82.00, 'disponible' => true],
            ['nombre' => 'Porcelanato Importado Bola Navidad', 'descripcion' => 'Porcelanato importado para pared principal con acabado brillante y diseño de mármol blanco con vetas grises/doradas.', 'codigo' => null, 'medidas' => '60x60 cm', 'marca' => null, 'category_id' => $cats['Porcelanatos grandes'], 'cantidad' => 20, 'precio' => 90.00, 'disponible' => true],

            // ========== Insertos y lápices ==========
            ['nombre' => 'Inserto Temática Zen', 'descripcion' => 'Pieza decorativa con diseño de piedras y toallas enfocada en la relajación.', 'codigo' => null, 'medidas' => '15x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 30, 'precio' => 18.00, 'disponible' => true],
            ['nombre' => 'Lápiz Metálico G 2 E / G 2 Golden', 'descripcion' => 'Listelo o lápiz metálico de terminación dorada/bronce en relieve.', 'codigo' => 'G 2 E / G 2 Golden', 'medidas' => '2x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 100, 'precio' => 12.00, 'disponible' => true],
            ['nombre' => 'Lápiz Sigzag Dorado', 'descripcion' => 'Listelo decorativo en relieve dorado con formato extendido.', 'codigo' => null, 'medidas' => '4x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 80, 'precio' => 14.00, 'disponible' => true],
            ['nombre' => 'Lápiz G 2 E Golden', 'descripcion' => 'Listelo metálico dorado en relieve que divide piezas vitrificadas.', 'codigo' => 'G 2 E Golden', 'medidas' => '2x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 100, 'precio' => 12.00, 'disponible' => true],
            ['nombre' => 'Lápiz Silver Plateado / S 2 E', 'descripcion' => 'Lápiz o listelo metálico plateado con diseño en relieve estriado.', 'codigo' => 'S 2 E', 'medidas' => '2x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 100, 'precio' => 11.00, 'disponible' => true],
            ['nombre' => 'Lápiz J 2-2 S', 'descripcion' => 'Lápiz decorativo metálico.', 'codigo' => 'J 2-2 S', 'medidas' => '2x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 80, 'precio' => 10.00, 'disponible' => true],
            ['nombre' => 'Lápiz J 2 2 G', 'descripcion' => 'Lápiz decorativo dorado.', 'codigo' => 'J 2 2 G', 'medidas' => '2x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 80, 'precio' => 10.00, 'disponible' => true],
            ['nombre' => 'Lápiz G 34', 'descripcion' => 'Lápiz decorativo para paneles centrales.', 'codigo' => 'G 34', 'medidas' => '2x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 70, 'precio' => 10.00, 'disponible' => true],
            ['nombre' => 'Lápiz de Vidrio', 'descripcion' => 'Lápiz decorativo fabricado en material de vidrio.', 'codigo' => null, 'medidas' => '1.5x50 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 60, 'precio' => 15.00, 'disponible' => true],
            ['nombre' => 'Listelo Sigzag Plateado', 'descripcion' => 'Listelo metálico plateado en relieve.', 'codigo' => null, 'medidas' => '4x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 80, 'precio' => 13.00, 'disponible' => true],
            ['nombre' => 'Listelo Zigzag Dorado', 'descripcion' => 'Listelo decorativo con diseño de greca geométrica.', 'codigo' => null, 'medidas' => '10x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 60, 'precio' => 16.00, 'disponible' => true],
            ['nombre' => 'Listelo Nacional Círculos Concéntricos', 'descripcion' => 'Listelo nacional con diseño de círculos concéntricos en colores rojo y blanco.', 'codigo' => null, 'medidas' => '7x36 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 70, 'precio' => 12.00, 'disponible' => true],
            ['nombre' => 'Listelo Amapolas', 'descripcion' => 'Listelo o inserto con diseño floral de rosas/amapolas negras sobre fondo blanco con bordes plateados.', 'codigo' => null, 'medidas' => '10x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 50, 'precio' => 18.00, 'disponible' => true],
            ['nombre' => 'Inserto Ondas 20x60', 'descripcion' => 'Inserto decorativo complementario para la serie Onda Gris.', 'codigo' => null, 'medidas' => '20x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 40, 'precio' => 22.00, 'disponible' => true],
            ['nombre' => 'Inserto Importado Carolina Black', 'descripcion' => 'Panel decorativo central con patrón floral negro sobre fondo blanco.', 'codigo' => null, 'medidas' => '30x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 25, 'precio' => 35.00, 'disponible' => true],
            ['nombre' => 'Inserto Importado Goku', 'descripcion' => 'Inserto decorativo temático animado.', 'codigo' => null, 'medidas' => '20x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 20, 'precio' => 28.00, 'disponible' => true],
            ['nombre' => 'Inserto Kashmir Silver', 'descripcion' => 'Inserto decorativo con temática de Spa que muestra toallas negras, jabonera y una flor blanca.', 'codigo' => null, 'medidas' => '20x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 30, 'precio' => 25.00, 'disponible' => true],
            ['nombre' => 'Inserto Importado Roswell', 'descripcion' => 'Inserto con temática de Spa con flores azules y toallas.', 'codigo' => null, 'medidas' => '15x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 30, 'precio' => 24.00, 'disponible' => true],
            ['nombre' => 'Inserto Importado Selene BI Selene', 'descripcion' => 'Inserto decorativo con diseño de esferas/burbujas en tonos bronce.', 'codigo' => null, 'medidas' => '15x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 25, 'precio' => 26.00, 'disponible' => true],
            ['nombre' => 'Inserto Importado Esferas Beige', 'descripcion' => 'Inserto decorativo con diseño de burbujas en tonos bronce/marrón.', 'codigo' => null, 'medidas' => '30x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 20, 'precio' => 32.00, 'disponible' => true],
            ['nombre' => 'Inserto Adicional Temática Spa/Relajación', 'descripcion' => 'Inserto decorativo complementario para pared derecha.', 'codigo' => null, 'medidas' => null, 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 25, 'precio' => 22.00, 'disponible' => true],
            ['nombre' => 'Inserto Importado Botánico', 'descripcion' => 'Panel decorativo de fondo con estampado botánico de hojas verdes tropicales sobre fondo blanco.', 'codigo' => null, 'medidas' => '60x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 15, 'precio' => 45.00, 'disponible' => true],
            ['nombre' => 'Inserto Importado Plumas', 'descripcion' => 'Panel decorativo con patrón de plumas negras y grises.', 'codigo' => null, 'medidas' => '30x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 20, 'precio' => 38.00, 'disponible' => true],
            ['nombre' => 'Inserto de Cocina Frutas', 'descripcion' => 'Inserto de cocina con diseño de tazas de fresas, uvas y utensilios de cocina.', 'codigo' => null, 'medidas' => '20x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 25, 'precio' => 30.00, 'disponible' => true],
            ['nombre' => 'Inserto de Cocina Tetera', 'descripcion' => 'Inserto de cocina con diseño de teteras plateadas, tazas y cafetera de prensa.', 'codigo' => null, 'medidas' => '20x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 25, 'precio' => 30.00, 'disponible' => true],
            ['nombre' => 'Inserto de Cocina Vajilla', 'descripcion' => 'Inserto de cocina con diseño de teteras blancas, tazas de té y cuencos decorativos en tonos dorados y marrones.', 'codigo' => null, 'medidas' => '20x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 25, 'precio' => 30.00, 'disponible' => true],
            ['nombre' => 'Inserto de Cocina Chef', 'descripcion' => 'Inserto de cocina con diseño de ollas negras, mortero, reloj y especias.', 'codigo' => null, 'medidas' => '20x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 25, 'precio' => 30.00, 'disponible' => true],
            ['nombre' => 'Inserto Importado 30x60', 'descripcion' => 'Inserto complementario para la serie Murete Aston.', 'codigo' => null, 'medidas' => '30x60 cm', 'marca' => null, 'category_id' => $cats['Insertos y lápices'], 'cantidad' => 20, 'precio' => 34.00, 'disponible' => true],

            // ========== Combinaciones ==========
            ['nombre' => 'Combinación Zen + Onda Gris', 'descripcion' => 'Combinación del Cerámico Nacional Serie Zen (círculos concéntricos) con el Cerámico Nacional Serie Onda Gris (patrón geométrico 3D). Ideal para crear contrastes de relieve en paredes principales.', 'codigo' => null, 'medidas' => '30x60 cm + 30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Combinaciones'], 'cantidad' => 15, 'precio' => 62.00, 'disponible' => true],
            ['nombre' => 'Combinación Ladrillo Superior + Inferior', 'descripcion' => 'Juego completo de Cerámico Nacional Serie Ladrillo Café para pared superior (LG 36071 A) e inferior (LG 36071 B). Logra un acabado texturizado uniforme de ladrillo beige y marrón.', 'codigo' => 'LG 36071 A + B', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Combinaciones'], 'cantidad' => 20, 'precio' => 55.00, 'disponible' => true],
            ['nombre' => 'Combinación Pasión White + Red', 'descripcion' => 'Set de Cerámicos Nacionales Pasión en blanco (pared izquierda) y rojo (pared derecha) con relieve tipo diamante. Perfecto para crear un impacto visual simétrico.', 'codigo' => null, 'medidas' => '27x45 cm', 'marca' => 'San Lorenzo', 'category_id' => $cats['Combinaciones'], 'cantidad' => 18, 'precio' => 52.00, 'disponible' => true],
            ['nombre' => 'Combinación Canvas Azul + Larizza Blanco', 'descripcion' => 'Juego deCerámico Nacional Canvas Azul (pared inferior izquierda) con Cerámico Nacional Larizza Blanco (pared superior izquierda). Contraste de color y textura.', 'codigo' => null, 'medidas' => '27x45 cm', 'marca' => 'San Lorenzo', 'category_id' => $cats['Combinaciones'], 'cantidad' => 15, 'precio' => 50.00, 'disponible' => true],
            ['nombre' => 'Combinación Onda Negro + Onda Gris', 'descripcion' => 'Set de Porcelanatos Nacionales Onda Negro (LG 36072 D, pared lateral izquierda) y Onda Gris (LG 36072 C, pared derecha de fondo). Contraste de ondas oscuras y claras.', 'codigo' => 'LG 36072 D + C', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Combinaciones'], 'cantidad' => 15, 'precio' => 68.00, 'disponible' => true],
            ['nombre' => 'Combinación Murete Aston + Inserto 30x60', 'descripcion' => 'Porcelanato Importado Murete Aston (textura piedra apilada) más su Inserto complementario 30x60. Ideal para paredes con acabado de piedra natural.', 'codigo' => null, 'medidas' => '60x60 cm + 30x60 cm', 'marca' => 'Typhoon', 'category_id' => $cats['Combinaciones'], 'cantidad' => 10, 'precio' => 110.00, 'disponible' => true],
            ['nombre' => 'Combinación Madera Nevado + Paquetón Golden', 'descripcion' => 'Combinación de Porcelanato Importado Madera Nevado (Taylor, 60x60) con Porcelanato Nacional Paquetón Golden (San Lorenzo, 20x61 cm). Texturas amaderadas en diferentes formatos.', 'codigo' => null, 'medidas' => '60x60 cm + 20x61 cm', 'marca' => 'Taylor + San Lorenzo', 'category_id' => $cats['Combinaciones'], 'cantidad' => 12, 'precio' => 98.00, 'disponible' => true],
            ['nombre' => 'Combinación Blanco Brillante + Calafate Grey', 'descripcion' => 'Cerámico Nacional Blanco Brillante (LG 36001) como base más Porcelanato Importado Calafate Grey (Taylor) como pared principal. Base lisa con veta marmoleada.', 'codigo' => 'LG 36001 + 311007995', 'medidas' => '30x60 cm', 'marca' => 'Porcelatino + Taylor', 'category_id' => $cats['Combinaciones'], 'cantidad' => 15, 'precio' => 68.00, 'disponible' => true],
            ['nombre' => 'Combinación LFG 66018 + Negro Mate', 'descripcion' => 'Porcelanato Nacional LFG 66018 (mármol gris veteado, 60x60) para piso y paredes, más Porcelanato Nacional Negro Mate (LFG 66098) para acentos oscuros.', 'codigo' => 'LFG 66018 + LFG 66098', 'medidas' => '60x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Combinaciones'], 'cantidad' => 20, 'precio' => 80.00, 'disponible' => true],
            ['nombre' => 'Combinación Carrara Blanco + Gris Mate', 'descripcion' => 'Porcelanato Nacional Carrara Blanco (WP 66061) para paredes y fondos, más Porcelanato Nacional Gris Mate (WFG 66002) para piso. Estilo clásico y moderno.', 'codigo' => 'WP 66061 + WFG 66002', 'medidas' => '60x60 cm', 'marca' => 'Porcelatino', 'category_id' => $cats['Combinaciones'], 'cantidad' => 20, 'precio' => 78.00, 'disponible' => true],

            // ========== Componentes (Sanitarios y Mobiliario) ==========
            ['nombre' => 'Inodoro y Urinario Boné', 'descripcion' => 'Sanitarios individuales en color crema de la marca Frencia.', 'codigo' => null, 'medidas' => null, 'marca' => 'Frencia', 'category_id' => $cats['Componentes'], 'cantidad' => 10, 'precio' => 280.00, 'disponible' => true],
            ['nombre' => 'Juego de Baño One Piece Boné', 'descripcion' => 'Inodoro One Piece con lavatorio de pedestal a juego en color Boné.', 'codigo' => null, 'medidas' => null, 'marca' => 'Frencia', 'category_id' => $cats['Componentes'], 'cantidad' => 8, 'precio' => 520.00, 'disponible' => true],
            ['nombre' => 'Modelo Palermo One Piece', 'descripcion' => 'Inodoro One Piece y lavatorio de pedestal en color Boné.', 'codigo' => null, 'medidas' => null, 'marca' => 'Frencia', 'category_id' => $cats['Componentes'], 'cantidad' => 6, 'precio' => 550.00, 'disponible' => true],
            ['nombre' => 'Modelo One Piece Blanco', 'descripcion' => 'Inodoro blanco de una sola pieza.', 'codigo' => null, 'medidas' => null, 'marca' => 'Frencia', 'category_id' => $cats['Componentes'], 'cantidad' => 12, 'precio' => 480.00, 'disponible' => true],
            ['nombre' => 'Juego de Baño Pedestal Blanco', 'descripcion' => 'Taza y tanque con manilla y lavatorio de pedestal en color blanco brillante.', 'codigo' => null, 'medidas' => null, 'marca' => 'Trébol', 'category_id' => $cats['Componentes'], 'cantidad' => 10, 'precio' => 380.00, 'disponible' => true],
            ['nombre' => 'Sanitario Dos Piezas Blanco', 'descripcion' => 'Taza y tanque de dos piezas con lavatorio de pedestal blanco.', 'codigo' => null, 'medidas' => null, 'marca' => 'Trébol', 'category_id' => $cats['Componentes'], 'cantidad' => 15, 'precio' => 320.00, 'disponible' => true],
            ['nombre' => 'Sanitario One Piece Orange Blanco', 'descripcion' => 'Taza y tanque con pulsador en color blanco brillante con lavatorio de pedestal.', 'codigo' => null, 'medidas' => null, 'marca' => 'Orange', 'category_id' => $cats['Componentes'], 'cantidad' => 8, 'precio' => 490.00, 'disponible' => true],
            ['nombre' => 'Inodoro Smart Gris Mate', 'descripcion' => 'Inodoro de tanque bajo, diseño elongado y pulsador cromado de doble descarga.', 'codigo' => null, 'medidas' => null, 'marca' => 'Taylor', 'category_id' => $cats['Componentes'], 'cantidad' => 10, 'precio' => 620.00, 'disponible' => true],
            ['nombre' => 'Inodoro One Piece Negro y Oro', 'descripcion' => 'Pieza de diseño aerodinámico importada con acabado vitrificado negro y línea dorada perimetral.', 'codigo' => '2070 VG', 'medidas' => null, 'marca' => null, 'category_id' => $cats['Componentes'], 'cantidad' => 4, 'precio' => 890.00, 'disponible' => true],
            ['nombre' => 'Juego de Baño One Piece Vainsa / Twyford', 'descripcion' => 'Sanitario de una pieza de alta gama en color blanco brillante.', 'codigo' => null, 'medidas' => null, 'marca' => 'Vainsa / Twyford', 'category_id' => $cats['Componentes'], 'cantidad' => 5, 'precio' => 750.00, 'disponible' => true],
            ['nombre' => 'Inodoro One Piece Importado', 'descripcion' => 'Sanitario compacto de una pieza.', 'codigo' => '2064', 'medidas' => null, 'marca' => 'W.T.', 'category_id' => $cats['Componentes'], 'cantidad' => 8, 'precio' => 580.00, 'disponible' => true],
            ['nombre' => 'Urinario Infantil Baby', 'descripcion' => 'Modelos de urinario para niños disponibles en colores verde, guinda/vino y beige a juego.', 'codigo' => null, 'medidas' => null, 'marca' => null, 'category_id' => $cats['Componentes'], 'cantidad' => 15, 'precio' => 120.00, 'disponible' => true],
            ['nombre' => 'Repostero Aéreo Blanco Tiradores Dorados', 'descripcion' => 'Mueble aéreo de cocina con jaladores dorados rectos.', 'codigo' => null, 'medidas' => null, 'marca' => null, 'category_id' => $cats['Componentes'], 'cantidad' => 8, 'precio' => 350.00, 'disponible' => true],
            ['nombre' => 'Repostero Conjunto Blanco Metálico', 'descripcion' => 'Muebles de cocina superior e inferior con tiradores metálicos estándar.', 'codigo' => null, 'medidas' => null, 'marca' => null, 'category_id' => $cats['Componentes'], 'cantidad' => 6, 'precio' => 580.00, 'disponible' => true],
            ['nombre' => 'Repostero Aéreo Blanco Tiradores Ondulados', 'descripcion' => 'Mueble aéreo de cocina con tiradores metálicos de diseño ondulado.', 'codigo' => null, 'medidas' => null, 'marca' => null, 'category_id' => $cats['Componentes'], 'cantidad' => 8, 'precio' => 370.00, 'disponible' => true],
            ['nombre' => 'Mueble de Baño Minimalista Negro', 'descripcion' => 'Encimera para lavatorio tipo Bowl con base oscura.', 'codigo' => null, 'medidas' => null, 'marca' => null, 'category_id' => $cats['Componentes'], 'cantidad' => 10, 'precio' => 290.00, 'disponible' => true],

            // ========== Pegamentos ==========
            ['nombre' => 'Hatun Wasi Porcelanatos Blanco Extrafuerte', 'descripcion' => 'Pegamento de alta resistencia especialmente formulado para la instalación de porcelanatos. Su color blanco mejora notablemente el acabado final y ofrece una excelente adherencia en pisos y paredes, tanto en interiores como en exteriores.', 'codigo' => null, 'medidas' => 'Saco de 25 kg', 'marca' => 'Hatun Wasi', 'category_id' => $cats['Pegamentos'], 'cantidad' => 50, 'precio' => 38.00, 'disponible' => true],
            ['nombre' => 'SikaCeram-203 Blanco Flexible Impermeable', 'descripcion' => 'Adhesivo de calidad premium con tecnología impermeable Acqua Block y alta flexibilidad. Diseñado especialmente para fijar piezas de baja absorción como porcelanatos, brindando una mayor durabilidad y alta resistencia a la humedad.', 'codigo' => null, 'medidas' => 'Saco de 25 kg', 'marca' => 'Sika', 'category_id' => $cats['Pegamentos'], 'cantidad' => 40, 'precio' => 52.00, 'disponible' => true],
            ['nombre' => 'Chemita Blanco Extrafuerte', 'descripcion' => 'Pegamento de gran adherencia diseñado para la colocación de porcelanatos y revestimientos. Su fórmula extrafuerte asegura una fijación firme, segura y duradera en diferentes tipos de superficies.', 'codigo' => null, 'medidas' => 'Saco de 25 kg', 'marca' => 'Chema', 'category_id' => $cats['Pegamentos'], 'cantidad' => 45, 'precio' => 35.00, 'disponible' => true],
            ['nombre' => 'Chemayolic Extrafuerte Blanco', 'descripcion' => 'Adhesivo con polímeros que proporciona máxima adherencia y una alta resistencia a la humedad. Está recomendado para la instalación de porcelanatos y cerámicos en ambientes interiores y exteriores.', 'codigo' => null, 'medidas' => 'Saco de 25 kg', 'marca' => 'Chema', 'category_id' => $cats['Pegamentos'], 'cantidad' => 40, 'precio' => 42.00, 'disponible' => true],
            ['nombre' => 'Chemayolic Blanco Flexible', 'descripcion' => 'Pegamento con polímeros de alto desempeño y flexibilidad. Es ideal para ser aplicado en superficies sometidas a movimientos o variaciones drásticas de temperatura, garantizando una excelente fijación y un acabado profesional.', 'codigo' => null, 'medidas' => 'Saco de 25 kg', 'marca' => 'Chema', 'category_id' => $cats['Pegamentos'], 'cantidad' => 35, 'precio' => 45.00, 'disponible' => true],
            ['nombre' => 'Hatun Wasi Cerámicos Gris Extrafuerte', 'descripcion' => 'Pegamento de color gris con fórmula de alta resistencia, desarrollado específicamente para la colocación de cerámicos en pisos y paredes. Asegura una unión firme y de larga duración.', 'codigo' => null, 'medidas' => 'Saco de 25 kg', 'marca' => 'Hatun Wasi', 'category_id' => $cats['Pegamentos'], 'cantidad' => 50, 'precio' => 32.00, 'disponible' => true],
            ['nombre' => 'Chemayolic Interiores', 'descripcion' => 'Adhesivo con polímeros formulado especialmente para la instalación económica y eficiente de cerámicos y mayólicas en espacios interiores. Ofrece una buena adherencia y gran facilidad de aplicación.', 'codigo' => null, 'medidas' => 'Saco de 25 kg', 'marca' => 'Chema', 'category_id' => $cats['Pegamentos'], 'cantidad' => 50, 'precio' => 28.00, 'disponible' => true],
            ['nombre' => 'Chema Súper Porcelana', 'descripcion' => 'Adhesivo especializado para la instalación de porcelanatos de alta calidad. Proporciona una excelente adherencia, óptima resistencia y un acabado completamente seguro para proyectos constructivos exigentes.', 'codigo' => null, 'medidas' => null, 'marca' => 'Chema', 'category_id' => $cats['Pegamentos'], 'cantidad' => 30, 'precio' => 48.00, 'disponible' => true],

            // ========== Componentes (Aditivos y Químicos) ==========
            ['nombre' => 'Aditivos para Construcción Línea Chema', 'descripcion' => 'Gama de productos líquidos especializados que mejoran la adherencia, la impermeabilización y la limpieza en trabajos de instalación de revestimientos. Incluye Chema Clean (limpiador multiuso), Chema Primer y Chema Sella Fragua.', 'codigo' => null, 'medidas' => null, 'marca' => 'Chema', 'category_id' => $cats['Componentes'], 'cantidad' => 30, 'precio' => 25.00, 'disponible' => true],

            // ========== Accesorios ==========
            ['nombre' => 'Griferías Línea Kariy Collect', 'descripcion' => 'Línea de griferías modernas con diseños elegantes y acabados metálicos de alta calidad (disponibles en tonos negro mate, dorado satinado y cromado brillante). Ofrecen durabilidad, alta funcionalidad y estilo para baños y cocinas.', 'codigo' => null, 'medidas' => null, 'marca' => 'Kariy Collect', 'category_id' => $cats['Accesorios'], 'cantidad' => 20, 'precio' => 85.00, 'disponible' => true],
            ['nombre' => 'Crucetas de Precisión con Tomador a Mano', 'descripcion' => 'Separadores plásticos de alta precisión que aseguran una distancia uniforme y milimétrica entre las piezas cerámicas o los porcelanatos durante el fraguado. Garantizan una instalación perfectamente alineada.', 'codigo' => null, 'medidas' => null, 'marca' => 'Inversiones Superplas-T S.A.C.', 'category_id' => $cats['Accesorios'], 'cantidad' => 200, 'precio' => 8.00, 'disponible' => true],
            ['nombre' => 'Arco Nivelador (Sistema de Nivelación)', 'descripcion' => 'Elemento plástico del sistema de nivelación, ideal para lograr acabados perfectos y evitar cejas o desniveles en pisos y paredes. Fabricados en material resistente, permiten una instalación uniforme.', 'codigo' => null, 'medidas' => '1 mm', 'marca' => null, 'category_id' => $cats['Accesorios'], 'cantidad' => 100, 'precio' => 15.00, 'disponible' => true],
            ['nombre' => 'Cuña Niveladora Premium', 'descripcion' => 'Componente reutilizable del sistema de nivelación que facilita la colocación y el ajuste preciso de los cerámicos. Su diseño asegura una correcta alineación presionando la baldosa uniformemente.', 'codigo' => null, 'medidas' => null, 'marca' => null, 'category_id' => $cats['Accesorios'], 'cantidad' => 100, 'precio' => 18.00, 'disponible' => true],
            ['nombre' => 'Nivelador Tornado (Nivelador Reutilizable Premium)', 'descripcion' => 'Sistema de nivelación innovador y reutilizable que optimiza la instalación de baldosas. Incluye una llave de ajuste mecánico de precisión para regular la presión, garantizando una nivelación eficiente y ahorro de costos en cada proyecto.', 'codigo' => null, 'medidas' => 'Paquete de 50 unidades', 'marca' => null, 'category_id' => $cats['Accesorios'], 'cantidad' => 50, 'precio' => 35.00, 'disponible' => true],
            ['nombre' => 'Alicate Nivelador', 'descripcion' => 'Herramienta o alicate profesional metálico/plástico para el sistema de nivelación de cerámicos. Facilita la instalación ejerciendo la presión exacta requerida, mejora el ajuste y ayuda a lograr un acabado uniforme reduciendo la fatiga del instalador.', 'codigo' => null, 'medidas' => null, 'marca' => null, 'category_id' => $cats['Accesorios'], 'cantidad' => 40, 'precio' => 45.00, 'disponible' => true],
            ['nombre' => 'Nivelador Liviano', 'descripcion' => 'Herramienta complementaria práctica y resistente diseñada para nivelar cerámicos con mayor velocidad y precisión en trabajos rápidos de pisos y paredes.', 'codigo' => null, 'medidas' => null, 'marca' => null, 'category_id' => $cats['Accesorios'], 'cantidad' => 50, 'precio' => 22.00, 'disponible' => true],
        ];

        foreach ($products as $data) {
            Product::create($data);
        }

        // Assign ambiente values deterministically per category via pivot
        $ambienteCycle = [
            'Cerámicos'              => ['Baño', 'Cocina', 'Sala', 'Baño'],
            'Porcelanatos'            => ['Sala', 'Comedor', 'Terraza', 'Sala'],
            'Tablones'               => ['Sala', 'Dormitorio', 'Fachadas'],
            'Revestimientos para pared' => ['Sala', 'Fachadas', 'Baño'],
            'Porcelanatos grandes'    => ['Sala', 'Comedor', 'Terraza', 'Sala'],
            'Insertos y lápices'      => ['Baño', 'Cocina', 'Baño'],
            'Combinaciones'           => ['Sala', 'Baño', 'Cocina'],
            'Componentes'             => ['Baño', 'Cocina'],
            'Pegamentos'              => [null],
            'Accesorios'              => [null],
        ];

        $ambModelMap = [];
        foreach (['Baño', 'Cocina', 'Sala', 'Comedor', 'Dormitorio', 'Terraza', 'Fachadas'] as $name) {
            $ambModelMap[$name] = \App\Models\Ambiente::firstOrCreate(
                ['slug' => $name],
                ['nombre' => $name, 'icono' => ''],
            );
        }

        $catCounter = [];
        $allProducts = Product::orderBy('id')->get();
        foreach ($allProducts as $product) {
            $slug = $product->category?->slug;
            if (!$slug || !isset($ambienteCycle[$slug])) continue;
            $catCounter[$slug] = ($catCounter[$slug] ?? 0);
            $cycle = $ambienteCycle[$slug];
            $ambName = $cycle[$catCounter[$slug] % count($cycle)];
            $catCounter[$slug]++;
            if ($ambName && isset($ambModelMap[$ambName])) {
                $product->ambientes()->syncWithoutDetaching([$ambModelMap[$ambName]->id]);
            }
        }

        if ($this->command) {
            $this->command->info('Productos reales insertados: ' . count($products));
        }
    }
}
